-- MySQL Script generated by MySQL Workbench
-- Wed Jan 30 15:47:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema openFruit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `openFruit` ;

-- -----------------------------------------------------
-- Schema openFruit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openFruit` DEFAULT CHARACTER SET utf8 ;
USE `openFruit` ;

-- -----------------------------------------------------
-- Table `openFruit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openFruit`.`user` ;

CREATE TABLE IF NOT EXISTS `openFruit`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openFruit`.`offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openFruit`.`offer` ;

CREATE TABLE IF NOT EXISTS `openFruit`.`offer` (
  `idoffer` INT NOT NULL AUTO_INCREMENT,
  `weight` DECIMAL NULL,
  `amount` INT NOT NULL,
  `product` VARCHAR(255) NOT NULL,
  `date_time_of_entry` DATETIME NOT NULL,
  PRIMARY KEY (`idoffer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openFruit`.`user_has_offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openFruit`.`user_has_offer` ;

CREATE TABLE IF NOT EXISTS `openFruit`.`user_has_offer` (
  `user_iduser` INT NOT NULL,
  `offerings_idofferings` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `offerings_idofferings`),
  INDEX `fk_user_has_offerings_offerings1_idx` (`offerings_idofferings` ASC),
  INDEX `fk_user_has_offerings_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_offerings_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `openFruit`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_offerings_offerings1`
    FOREIGN KEY (`offerings_idofferings`)
    REFERENCES `openFruit`.`offer` (`idoffer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
